*&---------------------------------------------------------------------*
*& Include          /PM11/AUTOPOSTING_TOP
*&---------------------------------------------------------------------*
TYPES: BEGIN OF ty_display,
         mdoc     TYPE imrg-mdocm,
         message  TYPE string,
         conf_msg TYPE string,
       END OF ty_display,
       BEGIN OF ty_work_order,
         message TYPE string,
       END OF ty_work_order,
       BEGIN OF ty_released,
         aufnr TYPE aufnr,
         arbei TYPE arbeit,
         vornr TYPE vornr,
       END OF ty_released,
       BEGIN OF ty_ord_list,
         aufnr TYPE aufnr,
       END OF ty_ord_list,
       BEGIN OF ty_conf_msg,
         conf_msg TYPE string,
       END OF ty_conf_msg,
       BEGIN OF ty_confirmed_order,
         confirmed_order TYPE aufnr,
       END OF ty_confirmed_order,
       BEGIN OF ty_teco_msg,
         teco_msg TYPE string,
       END OF ty_teco_msg,
       BEGIN OF ty_out_operation,
         aufnr TYPE aufk-aufnr,
         objnr TYPE aufk-objnr,
         werks TYPE aufk-werks,
         vaplz TYPE aufk-vaplz,
         wawrk TYPE aufk-wawrk,
         vornr TYPE afvc-vornr,
         arbei TYPE afvv-arbei,
         ismnw TYPE afvv-ismnw,
         ofmnw TYPE afvv-ofmnw,
         arbeh TYPE afvv-arbeh,
         fsavd TYPE afvv-fsavd,
         fsedd TYPE afvv-fsedd,
         stat  TYPE jest-stat,
         inact TYPE jest-inact,
       END OF ty_out_operation,

       BEGIN OF ty_jest,
         objnr TYPE jest-objnr,
         stat  TYPE jest-stat,
         inact TYPE jest-inact,
       END OF ty_jest.

DATA: i_displ_mdoc       TYPE STANDARD TABLE OF ty_display,
      i_work_order       TYPE STANDARD TABLE OF ty_work_order,
      i_bapi_work_order  TYPE STANDARD TABLE OF ty_work_order,
      i_released         TYPE STANDARD TABLE OF ty_released,
      i_confirmed_orders TYPE STANDARD TABLE OF ty_released,
      i_conf_msg         TYPE STANDARD TABLE OF ty_conf_msg,
      i_bapi_timeconf    TYPE STANDARD TABLE OF ty_conf_msg,
      i_final_order      TYPE STANDARD TABLE OF ty_ord_list,
      i_timeconf         TYPE STANDARD TABLE OF ty_ord_list,
      i_teco_msg         TYPE STANDARD TABLE OF ty_teco_msg,
      i_bapi_teco        TYPE STANDARD TABLE OF ty_teco_msg,
      i_mdoc_final       TYPE STANDARD TABLE OF imrg_mdocm.

DATA: gv_point TYPE imrc_point.
DATA: g_out_operation TYPE STANDARD TABLE OF ty_out_operation,
      g_out_jest      TYPE STANDARD TABLE OF ty_jest,
      g_found         TYPE flag,
      g_tc_flag       TYPE flag.
