*&---------------------------------------------------------------------*
*& Include          /PM11/AUTOPOSTING_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b1.

PARAMETERS: p_plant TYPE werks_d OBLIGATORY,
            p_wkctr TYPE gewrk,
            p_werks TYPE werks_d.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
PARAMETERS: p_mdoc AS CHECKBOX.
SELECTION-SCREEN COMMENT (20) text-c01.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
PARAMETERS: p_orders AS CHECKBOX DEFAULT abap_true.
SELECTION-SCREEN COMMENT (20) text-c02.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
PARAMETERS: p_conf AS CHECKBOX DEFAULT abap_true.
SELECTION-SCREEN COMMENT (20) text-c03.
SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN BEGIN OF LINE.
*SELECTION-SCREEN POSITION 1.
*PARAMETERS: p_goods AS CHECKBOX.
*SELECTION-SCREEN COMMENT (20) text-c04.
*SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
PARAMETERS: p_teco AS CHECKBOX DEFAULT abap_true.
SELECTION-SCREEN COMMENT (20) text-c05.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK b1.
